server:
  port: 8080
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: test
          uri: lb://TEST
          predicates:
            - Path=/test/**
          filters:
            - StripPrefix=1
            - AddResponseHeader=X-Response-Foo, Bar
            - AddRequestHeader=test, Phoenix
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8079/eureka
    instance:
      prefer-ip-address: true

logging:
  level:
    root: info
